#!/usr/bin/env python

# Helper launcher for crytto.py - see crytto/main.py

import os
import sys

from crytto.main import run

# A bit of hackery to avoid python imports failures.
# This is just for development purposes, users ought to instead
# install crytto for PyPi.
realpath = os.path.realpath(__file__)
dirname = os.path.dirname(realpath)
sys.path.append(dirname)

run()
