#!/usr/bin/env python

# Helper launcher for filecrypt.py - see filecrypt/main.py

import os
import sys

from filecrypt.main import run

# A bit of hackery to avoid python imports failures.
# This is just for development purposes, users ought to instead
# install filecrypt for PyPi.
realpath = os.path.realpath(__file__)
dirname = os.path.dirname(realpath)
sys.path.append(dirname)

run()
